/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartRouteImport } from './routes/start'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesEcommerceGrowthRouteImport } from './routes/services.ecommerce-growth'
import { Route as ServicesGeoRouteImport } from './routes/services.geo'
import { Route as ServicesMarketplaceOptimizationRouteImport } from './routes/services.marketplace-optimization'
import { Route as ServicesPaidMarketingRouteImport } from './routes/services.paid-marketing'
import { Route as ServicesWebCreationRouteImport } from './routes/services.web-creation'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEcommerceGrowthRoute = ServicesEcommerceGrowthRouteImport.update({
  id: '/ecommerce-growth',
  path: '/ecommerce-growth',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGeoRoute = ServicesGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMarketplaceOptimizationRoute =
  ServicesMarketplaceOptimizationRouteImport.update({
    id: '/marketplace-optimization',
    path: '/marketplace-optimization',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPaidMarketingRoute = ServicesPaidMarketingRouteImport.update({
  id: '/paid-marketing',
  path: '/paid-marketing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebCreationRoute = ServicesWebCreationRouteImport.update({
  id: '/web-creation',
  path: '/web-creation',
  getParentRoute: () => ServicesRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ecommerce-growth': typeof ServicesEcommerceGrowthRoute
  '/services/geo': typeof ServicesGeoRoute
  '/services/marketplace-optimization': typeof ServicesMarketplaceOptimizationRoute
  '/services/paid-marketing': typeof ServicesPaidMarketingRoute
  '/services/web-creation': typeof ServicesWebCreationRoute
  '/work/$slug': typeof WorkSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ecommerce-growth': typeof ServicesEcommerceGrowthRoute
  '/services/geo': typeof ServicesGeoRoute
  '/services/marketplace-optimization': typeof ServicesMarketplaceOptimizationRoute
  '/services/paid-marketing': typeof ServicesPaidMarketingRoute
  '/services/web-creation': typeof ServicesWebCreationRoute
  '/work/$slug': typeof WorkSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ecommerce-growth': typeof ServicesEcommerceGrowthRoute
  '/services/geo': typeof ServicesGeoRoute
  '/services/marketplace-optimization': typeof ServicesMarketplaceOptimizationRoute
  '/services/paid-marketing': typeof ServicesPaidMarketingRoute
  '/services/web-creation': typeof ServicesWebCreationRoute
  '/work/$slug': typeof WorkSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/start'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/ecommerce-growth'
    | '/services/geo'
    | '/services/marketplace-optimization'
    | '/services/paid-marketing'
    | '/services/web-creation'
    | '/work/$slug'
    | '/industries/'
    | '/insights/'
    | '/services/'
    | '/work/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/sitemap.xml'
    | '/start'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/ecommerce-growth'
    | '/services/geo'
    | '/services/marketplace-optimization'
    | '/services/paid-marketing'
    | '/services/web-creation'
    | '/work/$slug'
    | '/industries'
    | '/insights'
    | '/services'
    | '/work'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/start'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/services/ecommerce-growth'
    | '/services/geo'
    | '/services/marketplace-optimization'
    | '/services/paid-marketing'
    | '/services/web-creation'
    | '/work/$slug'
    | '/industries/'
    | '/insights/'
    | '/services/'
    | '/work/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ecommerce-growth': {
      id: '/services/ecommerce-growth'
      path: '/ecommerce-growth'
      fullPath: '/services/ecommerce-growth'
      preLoaderRoute: typeof ServicesEcommerceGrowthRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/geo': {
      id: '/services/geo'
      path: '/geo'
      fullPath: '/services/geo'
      preLoaderRoute: typeof ServicesGeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/marketplace-optimization': {
      id: '/services/marketplace-optimization'
      path: '/marketplace-optimization'
      fullPath: '/services/marketplace-optimization'
      preLoaderRoute: typeof ServicesMarketplaceOptimizationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/paid-marketing': {
      id: '/services/paid-marketing'
      path: '/paid-marketing'
      fullPath: '/services/paid-marketing'
      preLoaderRoute: typeof ServicesPaidMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/web-creation': {
      id: '/services/web-creation'
      path: '/web-creation'
      fullPath: '/services/web-creation'
      preLoaderRoute: typeof ServicesWebCreationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesEcommerceGrowthRoute: typeof ServicesEcommerceGrowthRoute
  ServicesGeoRoute: typeof ServicesGeoRoute
  ServicesMarketplaceOptimizationRoute: typeof ServicesMarketplaceOptimizationRoute
  ServicesPaidMarketingRoute: typeof ServicesPaidMarketingRoute
  ServicesWebCreationRoute: typeof ServicesWebCreationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesEcommerceGrowthRoute: ServicesEcommerceGrowthRoute,
  ServicesGeoRoute: ServicesGeoRoute,
  ServicesMarketplaceOptimizationRoute: ServicesMarketplaceOptimizationRoute,
  ServicesPaidMarketingRoute: ServicesPaidMarketingRoute,
  ServicesWebCreationRoute: ServicesWebCreationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
